### ISSUE TITLE
/kaomoji :list doesn't seem to work

### ISSUE THREAD

**Issue by andyfryy** [jlmart88/kaomoji-slack#2]
Hi, 

Awesome slack app! Although the list functionality doesn't seem to be working on my end. When I type: 

`/kaomoji :list` 

What I get is this. Slack thinks I'm trying to add an emoji. 

![screen shot 2018-10-17 at 10 52 00 am](https://user-images.githubusercontent.com/37874378/47095198-c90e8000-d1fa-11e8-859c-0f51e6a18e3e.png)

**Comment by jlmart88** [comment]
Just tested this out, and it looks like Slack changed at some point to bring up the emoji autocomplete even when in the middle of a slash command. This is super annoying, I'll see if there is any way to work around this without adding a breaking change (this might even an unintentional change in behavior on Slack's part).

In the meantime, you can prevent the emoji auto-complete by typing in a space after `:list`. Hope that helps!

**Comment by jlmart88** [comment]
Actually, looking back at the original gifs I made on the website, it appears that the emoji window always did appear, its just that `:list` never had any emoji results (oops). Looks like a change is required, thanks for pointing this out

**Comment by andyfryy** [comment]
No prob! Thank you in turn for the tip. Adding a space after `:list` did in fact work for me.
