### ISSUE TITLE
!list doesn't work

### ISSUE THREAD

**Issue by TyJaYo** [jlmart88/kaomoji-slack#9]
typing `/kao !list` brings up an empty menu
typing `/kaomoji !list` posts a random kaomoji

**Comment by jlmart88** [comment]
Is this still an issue? I'm not able to reproduce this myself. If it is, could you take a screen shot or short clip of the behavior?

`!list` is supposed to bring up a text input field, in which you can search for kaomoji. So it will be empty at first until you type in a query
